import { test, expect } from '../fixtures/test';
import { DashboardPage } from '../pages/DashboardPage';
import { quickTransfers } from '../testData/dashboadData';

test('Make payment', async ({ page }) => {
    await page.goto('/pulpit.html');
  await page.getByRole('link', { name: 'płatności' }).click();
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).click();
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).fill('Niejadek');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'wpisz nazwę odbiorcy przelewu' }).fill('Radek Niejadek');
  await page.getByRole('textbox', { name: '__ ____ ____ ____ ____ ____' }).click();
  await page.getByRole('textbox', { name: '__ ____ ____ ____ ____ ____' }).fill('00 1111 2222 4444 5555 6666 77778');
  await page.locator('.i-show').first().click();
  await page.getByRole('textbox', { name: 'ulica i numer domu /' }).click();
  await page.getByRole('textbox', { name: 'ulica i numer domu /' }).fill('ul. Ładna 16B/13');
  await page.getByRole('textbox', { name: 'ulica i numer domu /' }).press('Tab');
  await page.getByRole('textbox', { name: 'kod pocztowy, miejscowość' }).fill('89-200');
  await page.getByRole('textbox', { name: 'kod pocztowy, miejscowość' }).press('Tab');
  await page.getByRole('textbox', { name: 'adres - trzecia linia' }).fill('Szubin');
  await page.locator('#form_amount').click();
  await page.locator('#form_amount').fill('2154,44');
  await page.locator('#form_after_transfer').click();
  await page.getByText('13 159,20', { exact: true }).click();
  await page.getByText('004,76').click();
  await page.getByText('przelew środków').click();
  await page.getByText('przelew środków').fill('Mój przelew');
  await page.locator('#form_date').click();
  await page.getByRole('combobox').nth(1).selectOption('3');
  await page.getByRole('link', { name: '1', exact: true }).click();
  await page.locator('.i-calendar').click();
  await page.locator('.i-calendar').click();
  await page.getByRole('radio', { name: 'ekspresowy' }).check();
  await page.getByText('5,00').click();
  await page.locator('#uniform-form_is_email > span').click();
  await page.locator('#form_email').click();
  await page.locator('#form_email').fill('test@test.ts');
  await page.getByText('dodaj do listy odbiorców Moż').click();
  await page.locator('#uniform-form_add_receiver > span').click();
  await page.locator('#form_receiver_name').click();
  await page.getByRole('checkbox', { name: 'jako zaufanego' }).check();
  await page.getByRole('link', { name: 'dalej' }).click();
  await expect(page.getByRole('link', { name: 'Przelew Udany' })).toBeVisible();
});